### ISSUE TITLE
link to issue tracker for feature request about the Google Assistant Service

### ISSUE THREAD

**Issue by proppy** [googlesamples/assistant-sdk-python#360]
This repository is meant to track issue about the Google Assistant Service Python bindings and its associated samples.

In order to avoid accumulating issue and feature request about the Google Assistant Service, and facilitate escalation, those should be tracked separately on a dedicated component on https://developers.google.com/issue-tracker/ similar to other Google APIs.

This issue tracks the following tasks:
- [ ] create the dedicated component
- [ ] updating README for `google-assistant-grpc` to reference it
- [ ] migrate existing https://github.com/googlesamples/assistant-sdk-python/labels/platform issue to the component
